builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: "386"
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    ignore:
      - goos: windows
        goarch: "386"

release:
  prerelease: auto

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ii64/obs-access-signer:latest"
      - "ii64/obs-access-signer:v{{ .Version }}"
    skip_push: auto